### ISSUE TITLE
checkout/clone and commit/push

### ISSUE THREAD

**Issue by paul-hammant** [tmpfs/rlx#9]
It would be a great feature to be able to checkout (clone) say _all_docs to the file system, edit them local, then commit/push them back to the CouchDB server.  Only the ones that have changed of course.

**Comment by tmpfs** [comment]
I like this idea, note that you can already do this using the `bulk push|pull` command without the feature of only pushing documents that have changed. Check out `rlx help bulk`.

Whilst I like the idea of git integration I think given the size of the code base right now and that it needs a lot of love I would not implement this for a while.

However, I am open to improving the `bulk push` command so that it possibly did a GET on each document first and compared the `ETag` header with the local document to see whether the document has been modified, the caveat with this is that local documents can be `.js` or `.json` and might not have `_id` etc.

So I would need to take the cli options convert each local document into how it would be represented on the server (attachments and everything) and then perform the comparison. Might end up having quite a few edge cases though.

Let me know if the `bulk` command does most of what you need.

**Comment by paul-hammant** [comment]
The bulk push operation (that was diff-aware) would be just great :)

I started something too a week and a bit ago - https://github.com/paul-hammant/couchscm - probably going no further.

You were quick to think of Git. The gargantuan-scale SCM out there is Perforce (Google used it up to 2012) and first Googlers made a Git front end for it, then the Perforce people made their own one for general use. First things first though - I'd be happy with 'just' checkin/checkout (clone/commit-push).

**Comment by tmpfs** [comment]
Cool, I'll keep this at the back of my mind and leave this issue open, but don't expect any movement on it in the near future.

For the moment, I need to bring this repository up to speed with my lint style and improve the documentation - I think those are the immediate priorities ;)

**Comment by paul-hammant** [comment]
Documentation is always a great thing to prioritize - especially when it's interwoven with examples too :)
